export const ESTIMATE_MAP_FIELDS = {
  products: "商品情報",
  contentType: "工事依頼内容",
  note: "備考",
  customerType: "お客様区分",
  companyName: "会社名",
  companyNamePhonetic: "会社名（フリガナ）",
  name: "お名前",
  namePhonetic: "お名前（フリガナ）",
  email: "メールアドレス",
  postCode: "郵便番号",
  district: "都道府県",
  city: "市区町村",
  address: "以降の住所",
  phoneNumber: "電話番号",
  cellPhone: "携帯番号",
  fax: "FAX番号",
  quoteType: "お見積り・ご注文",
  supplier: "現場名",
  supplierType: "建築の種別",
  purpose: "ご利用目的",
  paymentMethod: "お支払い方法",
  estimateDate: "納品ご希望予定日",
  budget: "ご予算",
  contactHistory: "お問い合わせ履歴",
};

export const ESTIMATION_ACCEPT_FIELDS = [
  "shop",
  "contentType",
  "contentType",
  "note",
  "files",
  "budget",
  "customerType",
  "companyName",
  "companyNamePhonetic",
  "name",
  "namePhonetic",
  "email",
  "postCode",
  "district",
  "city",
  "address",
  "phoneNumber",
  "cellPhone",
  "fax",
  "quoteType",
  "supplier",
  "supplierType",
  "purpose",
  "quotation",
  "discerning",
  "content",
  "paymentMethod",
  "estimateDate",
  "contactHistory",
  "products",
];
