export const PROPOSAL_MAP_FIELDS = {
  customerType: "お客様区分",
  companyName: "会社名",
  companyNamePhonetic: "会社名（フリガナ）",
  name: "お名前",
  namePhonetic: "お名前（フリガナ）",
  email: "メールアドレス",
  postCode: "郵便番号",
  district: "都道府県",
  city: "市区町村",
  address: "以降の住所",
  phoneNumber: "電話番号",
  cellPhone: "携帯番号",
  fax: "FAX番号",
  content: "お問い合わせ内容",
  supplier: "現場名",
  supplierType: "建築の種別",
  purpose: "ご利用目的",
  budget: "ご予算",
  files: "添付ファイル",
  contactHistory: "お問い合わせ履歴",
  products: "商品情報",
};
